# Generated by Django 5.2.1 on 2025-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconapp', '0003_plaza_delete_calendario_remove_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaza',
            old_name='precio',
            new_name='pago',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='ddireccion_evento',
            new_name='direccion_evento',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='nombre',
        ),
        migrations.AddField(
            model_name='plaza',
            name='nombre_plaza',
            field=models.CharField(default='Inflable Generico', max_length=100),
            preserve_default=False,
        ),
    ]
