# Generated by Django 5.2.1 on 2025-06-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinconapp', '0004_rename_precio_plaza_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='SinApellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plaza',
            name='pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='plaza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rinconapp.plaza'),
        ),
    ]
